name: account_book_admin
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  firebase_admin: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
